import type { Parcel } from '@/lib/types';

export const parcelData: Parcel[] = [
  // Tourism locations based on telecom visitor density data - Dense clusters and corridors
  
  // Al-Soudah Tourism Corridor (High density cluster)
  {
    id: 't001',
    name: 'Al-Soudah Peaks Area',
    position: { lat: 18.271, lng: 42.378 },
    type: 'Tourism',
    score: 95,
    viability: 'Excellent',
    description: 'Highest visitor concentration in Asir region - peak tourism traffic zone',
    investment: '$50M',
    visitorDensity: '2,850 visitors/day',
    investmentSuccess: '85% ROI expected',
    riskLevel: 'Low',
    timeToROI: '2.5 years',
    marketDemand: 'Very High'
  },
  {
    id: 't002',
    name: 'Al-Soudah Cable Car Station',
    position: { lat: 18.275, lng: 42.375 },
    type: 'Tourism',
    score: 92,
    viability: 'Excellent',
    description: 'Cable car terminus with continuous high visitor flow',
    investment: '$25M',
    visitorDensity: '2,650 visitors/day',
    investmentSuccess: '82% ROI expected',
    riskLevel: 'Low',
    timeToROI: '2.8 years',
    marketDemand: 'Very High'
  },
  {
    id: 't003',
    name: 'Al-Soudah Resort Complex',
    position: { lat: 18.268, lng: 42.382 },
    type: 'Tourism',
    score: 89,
    viability: 'Excellent',
    description: 'Resort area with consistent luxury tourism traffic',
    investment: '$45M',
    visitorDensity: '2,420 visitors/day',
    investmentSuccess: '79% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3 years',
    marketDemand: 'Very High'
  },
  {
    id: 't004',
    name: 'Al-Soudah Visitor Center',
    position: { lat: 18.273, lng: 42.380 },
    type: 'Tourism',
    score: 86,
    viability: 'Excellent',
    description: 'Main visitor hub with information and services',
    investment: '$15M',
    visitorDensity: '2,200 visitors/day',
    investmentSuccess: '76% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.2 years',
    marketDemand: 'Very High'
  },

  // Abha City Tourism Corridor (Dense urban cluster)
  {
    id: 't005',
    name: 'Abha City Center',
    position: { lat: 18.216, lng: 42.505 },
    type: 'Tourism',
    score: 88,
    viability: 'Excellent',
    description: 'Urban tourism hub with steady visitor flow and commercial activity',
    investment: '$25M',
    visitorDensity: '1,950 visitors/day',
    investmentSuccess: '78% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.2 years',
    marketDemand: 'Very High'
  },
  {
    id: 't006',
    name: 'Abha Palace Hotel District',
    position: { lat: 18.220, lng: 42.508 },
    type: 'Tourism',
    score: 85,
    viability: 'Excellent',
    description: 'Hotel district with high accommodation demand',
    investment: '$35M',
    visitorDensity: '1,780 visitors/day',
    investmentSuccess: '75% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.5 years',
    marketDemand: 'Very High'
  },
  {
    id: 't007',
    name: 'Abha Shopping District',
    position: { lat: 18.212, lng: 42.502 },
    type: 'Tourism',
    score: 82,
    viability: 'Good',
    description: 'Commercial area with shopping and dining attractions',
    investment: '$20M',
    visitorDensity: '1,650 visitors/day',
    investmentSuccess: '72% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.8 years',
    marketDemand: 'High'
  },
  {
    id: 't008',
    name: 'Abha Cultural Quarter',
    position: { lat: 18.218, lng: 42.510 },
    type: 'Tourism',
    score: 79,
    viability: 'Good',
    description: 'Cultural attractions and traditional architecture',
    investment: '$18M',
    visitorDensity: '1,520 visitors/day',
    investmentSuccess: '69% ROI expected',
    riskLevel: 'Low',
    timeToROI: '4 years',
    marketDemand: 'High'
  },
  {
    id: 't009',
    name: 'Abha Lake Park',
    position: { lat: 18.214, lng: 42.507 },
    type: 'Tourism',
    score: 76,
    viability: 'Good',
    description: 'Recreational lake area with family attractions',
    investment: '$22M',
    visitorDensity: '1,380 visitors/day',
    investmentSuccess: '66% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.2 years',
    marketDemand: 'High'
  },

  // Rijal Almaa Heritage Corridor
  {
    id: 't010',
    name: 'Rijal Almaa Heritage Village',
    position: { lat: 18.225, lng: 42.455 },
    type: 'Tourism',
    score: 90,
    viability: 'Excellent',
    description: 'UNESCO heritage site with traditional architecture',
    investment: '$15M',
    visitorDensity: '2,120 visitors/day',
    investmentSuccess: '80% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3 years',
    marketDemand: 'Very High'
  },
  {
    id: 't011',
    name: 'Rijal Almaa Museum Complex',
    position: { lat: 18.228, lng: 42.458 },
    type: 'Tourism',
    score: 87,
    viability: 'Excellent',
    description: 'Heritage museum with cultural exhibits',
    investment: '$12M',
    visitorDensity: '1,890 visitors/day',
    investmentSuccess: '77% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.3 years',
    marketDemand: 'Very High'
  },
  {
    id: 't012',
    name: 'Rijal Almaa Visitor Center',
    position: { lat: 18.222, lng: 42.452 },
    type: 'Tourism',
    score: 84,
    viability: 'Good',
    description: 'Main entry point with visitor services',
    investment: '$8M',
    visitorDensity: '1,720 visitors/day',
    investmentSuccess: '74% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.5 years',
    marketDemand: 'High'
  },

  // Mountain Road Tourism Corridor (Linear cluster)
  {
    id: 't013',
    name: 'Mountain View Point Alpha',
    position: { lat: 18.250, lng: 42.420 },
    type: 'Tourism',
    score: 75,
    viability: 'Good',
    description: 'Scenic viewpoint along mountain road',
    investment: '$10M',
    visitorDensity: '1,280 visitors/day',
    investmentSuccess: '65% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.5 years',
    marketDemand: 'High'
  },
  {
    id: 't014',
    name: 'Mountain View Point Beta',
    position: { lat: 18.245, lng: 42.425 },
    type: 'Tourism',
    score: 72,
    viability: 'Good',
    description: 'Secondary viewpoint with hiking trails',
    investment: '$8M',
    visitorDensity: '1,150 visitors/day',
    investmentSuccess: '62% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.8 years',
    marketDemand: 'Medium'
  },
  {
    id: 't015',
    name: 'Mountain Road Rest Area',
    position: { lat: 18.240, lng: 42.430 },
    type: 'Tourism',
    score: 69,
    viability: 'Good',
    description: 'Rest area with cafes and souvenir shops',
    investment: '$6M',
    visitorDensity: '1,020 visitors/day',
    investmentSuccess: '59% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '5 years',
    marketDemand: 'Medium'
  },

  // Khamis Mushait Tourism Zone
  {
    id: 't016',
    name: 'Khamis Mushait City Center',
    position: { lat: 18.300, lng: 42.733 },
    type: 'Tourism',
    score: 78,
    viability: 'Good',
    description: 'Regional hub with commercial and cultural attractions',
    investment: '$20M',
    visitorDensity: '1,420 visitors/day',
    investmentSuccess: '68% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.2 years',
    marketDemand: 'High'
  },
  {
    id: 't017',
    name: 'Khamis Mushait Mall District',
    position: { lat: 18.305, lng: 42.730 },
    type: 'Tourism',
    score: 74,
    viability: 'Good',
    description: 'Shopping and entertainment complex',
    investment: '$25M',
    visitorDensity: '1,250 visitors/day',
    investmentSuccess: '64% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.5 years',
    marketDemand: 'Medium'
  },
  {
    id: 't018',
    name: 'Khamis Mushait Airport Area',
    position: { lat: 18.295, lng: 42.738 },
    type: 'Tourism',
    score: 71,
    viability: 'Good',
    description: 'Airport vicinity with transit tourism potential',
    investment: '$15M',
    visitorDensity: '1,080 visitors/day',
    investmentSuccess: '61% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.8 years',
    marketDemand: 'Medium'
  },

  // Valley Tourism Corridor
  {
    id: 't019',
    name: 'Tanoumah Valley Entrance',
    position: { lat: 18.920, lng: 42.150 },
    type: 'Tourism',
    score: 68,
    viability: 'Fair',
    description: 'Valley entrance with eco-tourism potential',
    investment: '$12M',
    visitorDensity: '920 visitors/day',
    investmentSuccess: '58% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '5.2 years',
    marketDemand: 'Medium'
  },
  {
    id: 't020',
    name: 'Tanoumah Nature Reserve',
    position: { lat: 18.925, lng: 42.155 },
    type: 'Tourism',
    score: 65,
    viability: 'Fair',
    description: 'Protected area with wildlife and hiking',
    investment: '$10M',
    visitorDensity: '850 visitors/day',
    investmentSuccess: '55% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '5.5 years',
    marketDemand: 'Medium'
  },

  // Agriculture locations - Dense farming corridors and valleys
  
  // Wadi Al-Tallah Agricultural Corridor (Major farming zone)
  {
    id: 'a001',
    name: 'Wadi Al-Tallah Valley Center',
    position: { lat: 18.350, lng: 42.600 },
    type: 'Agriculture',
    score: 92,
    viability: 'Excellent',
    description: 'Central farming zone with highest market access',
    investment: '$40M',
    visitorDensity: '2,240 visitors/day',
    investmentSuccess: '82% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3 years',
    marketDemand: 'Very High'
  },
  {
    id: 'a002',
    name: 'Wadi Al-Tallah North Farm',
    position: { lat: 18.355, lng: 42.605 },
    type: 'Agriculture',
    score: 89,
    viability: 'Excellent',
    description: 'Northern section with premium soil quality',
    investment: '$35M',
    visitorDensity: '2,080 visitors/day',
    investmentSuccess: '79% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.2 years',
    marketDemand: 'Very High'
  },
  {
    id: 'a003',
    name: 'Wadi Al-Tallah South Farm',
    position: { lat: 18.345, lng: 42.595 },
    type: 'Agriculture',
    score: 86,
    viability: 'Excellent',
    description: 'Southern farming area with irrigation infrastructure',
    investment: '$32M',
    visitorDensity: '1,920 visitors/day',
    investmentSuccess: '76% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.5 years',
    marketDemand: 'Very High'
  },
  {
    id: 'a004',
    name: 'Wadi Al-Tallah Processing Center',
    position: { lat: 18.352, lng: 42.598 },
    type: 'Agriculture',
    score: 84,
    viability: 'Good',
    description: 'Central processing and packaging facility',
    investment: '$28M',
    visitorDensity: '1,780 visitors/day',
    investmentSuccess: '74% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.8 years',
    marketDemand: 'High'
  },

  // Abha Highland Agricultural Belt
  {
    id: 'a005',
    name: 'Abha Highland Farms Central',
    position: { lat: 18.250, lng: 42.480 },
    type: 'Agriculture',
    score: 85,
    viability: 'Excellent',
    description: 'Central highland farming with temperate crops',
    investment: '$30M',
    visitorDensity: '1,850 visitors/day',
    investmentSuccess: '75% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.5 years',
    marketDemand: 'Very High'
  },
  {
    id: 'a006',
    name: 'Abha Highland Farms East',
    position: { lat: 18.255, lng: 42.485 },
    type: 'Agriculture',
    score: 82,
    viability: 'Good',
    description: 'Eastern highland area with fruit orchards',
    investment: '$25M',
    visitorDensity: '1,720 visitors/day',
    investmentSuccess: '72% ROI expected',
    riskLevel: 'Low',
    timeToROI: '4 years',
    marketDemand: 'High'
  },
  {
    id: 'a007',
    name: 'Abha Highland Farms West',
    position: { lat: 18.245, lng: 42.475 },
    type: 'Agriculture',
    score: 79,
    viability: 'Good',
    description: 'Western highland with organic farming potential',
    investment: '$22M',
    visitorDensity: '1,580 visitors/day',
    investmentSuccess: '69% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.2 years',
    marketDemand: 'High'
  },
  {
    id: 'a008',
    name: 'Abha Highland Cold Storage',
    position: { lat: 18.252, lng: 42.478 },
    type: 'Agriculture',
    score: 77,
    viability: 'Good',
    description: 'Cold storage and distribution facility',
    investment: '$20M',
    visitorDensity: '1,450 visitors/day',
    investmentSuccess: '67% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.5 years',
    marketDemand: 'High'
  },

  // Khamis Mushait Agricultural Zone
  {
    id: 'a009',
    name: 'Khamis Mushait Coffee Plantation',
    position: { lat: 18.300, lng: 42.733 },
    type: 'Agriculture',
    score: 87,
    viability: 'Excellent',
    description: 'Premium coffee cultivation with processing facility',
    investment: '$25M',
    visitorDensity: '1,950 visitors/day',
    investmentSuccess: '77% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.3 years',
    marketDemand: 'Very High'
  },
  {
    id: 'a010',
    name: 'Khamis Coffee Processing Hub',
    position: { lat: 18.305, lng: 42.728 },
    type: 'Agriculture',
    score: 84,
    viability: 'Good',
    description: 'Coffee processing and roasting center',
    investment: '$20M',
    visitorDensity: '1,780 visitors/day',
    investmentSuccess: '74% ROI expected',
    riskLevel: 'Low',
    timeToROI: '3.8 years',
    marketDemand: 'High'
  },
  {
    id: 'a011',
    name: 'Khamis Agricultural Research',
    position: { lat: 18.295, lng: 42.735 },
    type: 'Agriculture',
    score: 81,
    viability: 'Good',
    description: 'Agricultural research and development center',
    investment: '$18M',
    visitorDensity: '1,620 visitors/day',
    investmentSuccess: '71% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.2 years',
    marketDemand: 'High'
  },

  // Al-Soudah Agricultural Area
  {
    id: 'a012',
    name: 'Al-Soudah Mountain Farms',
    position: { lat: 18.271, lng: 42.378 },
    type: 'Agriculture',
    score: 78,
    viability: 'Good',
    description: 'High-altitude specialty crop cultivation',
    investment: '$15M',
    visitorDensity: '1,480 visitors/day',
    investmentSuccess: '68% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.5 years',
    marketDemand: 'High'
  },
  {
    id: 'a013',
    name: 'Al-Soudah Herb Gardens',
    position: { lat: 18.275, lng: 42.375 },
    type: 'Agriculture',
    score: 75,
    viability: 'Good',
    description: 'Medicinal and culinary herb cultivation',
    investment: '$12M',
    visitorDensity: '1,320 visitors/day',
    investmentSuccess: '65% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.8 years',
    marketDemand: 'Medium'
  },

  // Rijal Almaa Valley Agricultural Corridor
  {
    id: 'a014',
    name: 'Rijal Almaa Valley Farms',
    position: { lat: 18.225, lng: 42.455 },
    type: 'Agriculture',
    score: 80,
    viability: 'Good',
    description: 'Traditional valley farming with heritage crops',
    investment: '$16M',
    visitorDensity: '1,580 visitors/day',
    investmentSuccess: '70% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.2 years',
    marketDemand: 'High'
  },
  {
    id: 'a015',
    name: 'Rijal Almaa Terraced Farms',
    position: { lat: 18.230, lng: 42.450 },
    type: 'Agriculture',
    score: 76,
    viability: 'Good',
    description: 'Traditional terraced farming system',
    investment: '$14M',
    visitorDensity: '1,380 visitors/day',
    investmentSuccess: '66% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.5 years',
    marketDemand: 'Medium'
  },
  {
    id: 'a016',
    name: 'Rijal Heritage Seed Bank',
    position: { lat: 18.228, lng: 42.458 },
    type: 'Agriculture',
    score: 73,
    viability: 'Fair',
    description: 'Heritage crop preservation and research',
    investment: '$10M',
    visitorDensity: '1,220 visitors/day',
    investmentSuccess: '63% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '5 years',
    marketDemand: 'Medium'
  },

  // Valley Agricultural Corridor
  {
    id: 'a017',
    name: 'Tanoumah Valley Agriculture',
    position: { lat: 18.920, lng: 42.150 },
    type: 'Agriculture',
    score: 70,
    viability: 'Fair',
    description: 'Valley agriculture with eco-tourism integration',
    investment: '$12M',
    visitorDensity: '1,080 visitors/day',
    investmentSuccess: '60% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '5.2 years',
    marketDemand: 'Medium'
  },
  {
    id: 'a018',
    name: 'Tanoumah Organic Farms',
    position: { lat: 18.925, lng: 42.155 },
    type: 'Agriculture',
    score: 67,
    viability: 'Fair',
    description: 'Organic farming with nature tourism appeal',
    investment: '$10M',
    visitorDensity: '950 visitors/day',
    investmentSuccess: '57% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '5.5 years',
    marketDemand: 'Medium'
  },

  // Additional scattered high-value points to connect corridors
  {
    id: 't021',
    name: 'Highway Rest Station Alpha',
    position: { lat: 18.280, lng: 42.520 },
    type: 'Tourism',
    score: 66,
    viability: 'Fair',
    description: 'Highway rest area with tourist services',
    investment: '$8M',
    visitorDensity: '880 visitors/day',
    investmentSuccess: '56% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '5.2 years',
    marketDemand: 'Medium'
  },
  {
    id: 't022',
    name: 'Mountain Pass Viewpoint',
    position: { lat: 18.260, lng: 42.440 },
    type: 'Tourism',
    score: 63,
    viability: 'Fair',
    description: 'Scenic mountain pass with photo opportunities',
    investment: '$6M',
    visitorDensity: '780 visitors/day',
    investmentSuccess: '53% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '5.8 years',
    marketDemand: 'Medium'
  },
  {
    id: 'a019',
    name: 'Mid-Valley Farm Hub',
    position: { lat: 18.310, lng: 42.580 },
    type: 'Agriculture',
    score: 72,
    viability: 'Good',
    description: 'Central valley farming with market access',
    investment: '$15M',
    visitorDensity: '1,180 visitors/day',
    investmentSuccess: '62% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '4.8 years',
    marketDemand: 'Medium'
  },
  {
    id: 'a020',
    name: 'Highland-Valley Connection',
    position: { lat: 18.290, lng: 42.520 },
    type: 'Agriculture',
    score: 69,
    viability: 'Fair',
    description: 'Bridge farming area connecting highland and valley zones',
    investment: '$13M',
    visitorDensity: '1,020 visitors/day',
    investmentSuccess: '59% ROI expected',
    riskLevel: 'Medium',
    timeToROI: '5.2 years',
    marketDemand: 'Medium'
  }
];
